$axure.loadCurrentPage({
  "url":"1、初始化.html",
  "generationDate":new Date(1425265392641.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7cc36c61b0884df98b598413532416f5",
    "type":"Axure:Page",
    "name":"1、初始化",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51c34dabc04e4a8a968be6f683330b56",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":757,
              "height":274}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f1abc5011845458adaefdb1b27f908",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5081DB},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d3791703f20454ea949c6b6fbf79702",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5081DB},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u5.png"}},
{
              "id":"1be623d7b56646d685e5b9cd31cf4bde",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7971d7e258f4f3dae011376f814b04e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u9.png"}},
{
              "id":"0065a7261ab0435ba068d185a29b5e89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5081DB},
                "location":{
                  "x":378,
                  "y":34},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c8f0af688424ab3ad8c65aca444e9d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5081DB},
                    "location":{
                      "x":378,
                      "y":34},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u7.png"}},
{
              "id":"84361a974a274a858dc776cc86690a1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":64},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84600017c94a4921a7ba2d26204ccb64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":64},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u11.png"}},
{
              "id":"d7e80391ae224ceba80c61f01aa37dc2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":378,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2cd4e0b6edb44c24845a3c4a25d9d696",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":378,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u1.png"}},
{
              "id":"563985062bbd470fa1eb8f9ceea45455",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":0},
                "size":{
                  "width":379,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"516d766687364dc5a503db7c9f736da6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":0},
                    "size":{
                      "width":379,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u3.png"}},
{
              "id":"208de70dbf1940a786d59197dff16306",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5081DB},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8455789af264fb2a836b180145f7e51",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5081DB},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u5.png"}},
{
              "id":"e870832c349f4b48a681bb7017724949",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5081DB},
                "location":{
                  "x":378,
                  "y":94},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f181bde2d9534179b0e4e73d76ef9687",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF5081DB},
                    "location":{
                      "x":378,
                      "y":94},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u7.png"}},
{
              "id":"6f8bf7cc8f274f5098ce7c509e44088e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1910240bce57482dae07141646b6f1b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u9.png"}},
{
              "id":"e3c8fbf912af4ec39ef61878aad99f48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":124},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"806801922db346b59f41b145f524a69b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":124},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u11.png"}},
{
              "id":"4e9f95c66264429ab27e731b3a0e62c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":154},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b0938a36d3f45659f3d0b51bba104a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":154},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u9.png"}},
{
              "id":"c671cd0d4d5a43ae9eec1b3e8427c907",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":154},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17567bbd95f641df98d8485183acaf94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":154},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u11.png"}},
{
              "id":"6f0ef1275dbc4451a84b8ce7ae7ac309",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":184},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3640c6c3069d4c7bac65011609598bba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":184},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u9.png"}},
{
              "id":"8e3211617340407b9840c2409a9c558d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":184},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e7f4f7885784d3a8c0cac40800aaf77",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":184},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u11.png"}},
{
              "id":"1c5cd72a6ea84c5bae5874a1e1d4ba39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":214},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cdc9e2756f324ba580f1b29eeb206bc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":214},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u9.png"}},
{
              "id":"ae790335b763486faf90f97b1fd6a3f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":214},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5e657d9c96f438bad1acc7c6494bbb2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":214},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u11.png"}},
{
              "id":"bd89b18efe6942fc8ba08f27014a20b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":244},
                "size":{
                  "width":378,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa36c9648f7747339639222dd22aab54",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":244},
                    "size":{
                      "width":378,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u33.png"}},
{
              "id":"9528e8da357a4988958e35ba5c31d6bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":244},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e6249cbc5384674890e4032248eb3f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":244},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u35.png"}}]},
{
          "id":"5a67c3bf04d24d28bf2520830b4f02c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":60,
              "y":43},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aac6ae45cc848aa859c4e983217f57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":60,
                  "y":43},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca3a679c5eb9441eb6cba41671e743f1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":373},
            "size":{
              "width":757,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1adad1ba1c0a47a7a6076df48bdc4bb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":102,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b455c81e06344d91ae3de954d4bbba73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":102,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u40.png"}},
{
              "id":"b036e4171ebd4fe58db504cf21e98b2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":0},
                "size":{
                  "width":102,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83496ebb66134a7fb146b9161d85100c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open object_update in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"object_update.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/1、初始化/u40.png"}},
{
              "id":"b079d562054b43ff9d00a16fb8f6169a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":0},
                "size":{
                  "width":174,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a90b53ebe8f433fa92cc219eb06fb26",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":0},
                    "size":{
                      "width":174,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u44.png"}},
{
              "id":"d465d644ff9b42f59a6413957efbb106",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":0},
                "size":{
                  "width":187,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45f1810dcf754350a219212ee041d0f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":0},
                    "size":{
                      "width":187,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u48.png"}},
{
              "id":"d07c527fb5944a7994b954dc394eba06",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":0},
                "size":{
                  "width":192,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f42c36172d24a37ac30fc0f6c86b4c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":0},
                    "size":{
                      "width":192,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u46.png"}},
{
              "id":"cb6bf0d7ee3e45f1a35a2866913af1a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1a2dca950eb4abaa1a1d11cc6e3a0c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"f6ee9dac1d8d4dcc97e0df90d02d7b5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":34},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e0f059c0b9b47d487f9d684216e3083",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":34},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open object_user in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"object_user.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"825cb2e7c6ae4ceab518dfc475380df2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":34},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1086a9f31e34e3ab89755f596f52772",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":34},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u54.png"}},
{
              "id":"b711e9ccf1ea44ec99f64f3970819d23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":34},
                "size":{
                  "width":192,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3e08feae3c04b108ba557c66bea5b72",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":34},
                    "size":{
                      "width":192,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u56.png"}},
{
              "id":"8913cc7d0d3b4a24a0b1f5e8ca157017",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":34},
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc3543fca25d42ff85dae039ae2f1a56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":34},
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u58.png"}},
{
              "id":"8c5c2a277cf94f7999e5a154d9873d14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ef71020c943436d92cb6f67962b5ba1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"5b38d9b0d90b41d2b1c4d8d678a5b00d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":64},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f07063b7d284e78afb7a34980ff99ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":64},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"515be87efe9f4827961b133c1a363527",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":64},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4362b499d734dc983b60cd26eb195d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":64},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u54.png"}},
{
              "id":"33e1af2960d34a45a28761f3f4530118",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":64},
                "size":{
                  "width":192,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e915ba7f38b340eeaf99f0a753c445ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":64},
                    "size":{
                      "width":192,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u56.png"}},
{
              "id":"e865c15f3db64c69a4ca37f8b5a366a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":64},
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cd151525f5249428b92850cf85ea271",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":64},
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u58.png"}},
{
              "id":"990cc7c463b2459491602e43784afbb6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd99422e40d840e1b0d608ffaaf91ae7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"08da6b090975445d939a4c7dca88df53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":94},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a256ce0e95cc47f39c4bd148dd468073",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":94},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"6b6d6fdf900e4180abb1ecb5d813ccc9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":94},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9365631dbe3a4c539e401e9c1f51170f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":94},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u54.png"}},
{
              "id":"0f6c25782fca4c6eb86184e414a40960",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":94},
                "size":{
                  "width":192,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47686ca3577d40279aef1345cd71d59b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":94},
                    "size":{
                      "width":192,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u56.png"}},
{
              "id":"174452a2f95447e7bd9cdb3fb0815436",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":94},
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e426e8ed34f44ea391f7c95fee795859",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":94},
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u58.png"}},
{
              "id":"dca7d695b39a4048b045b9aebf2663a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0cc0265dc64b46c4a317d092067bf210",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"244247b948a542728d706749ef7e925e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":124},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24e65b4662db4eb2a6e00851750d3c94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":124},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"5467bddfa0da4458a1589bf67f9da9cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":124},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d38a5e0288104dd585bf5b3aeca7f5ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":124},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u54.png"}},
{
              "id":"253dec0fb88546cfafa47b12fe002159",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":124},
                "size":{
                  "width":192,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d86fbbc295234485bf8bb72460d9312e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":124},
                    "size":{
                      "width":192,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u56.png"}},
{
              "id":"4ad9eb7bbb8d4dde97810e7529d6dc5a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":124},
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72dac123d684418baa06f3d6c2641b4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":124},
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u58.png"}},
{
              "id":"efd6094263d54432a3518e6572931d86",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":154},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb9536880ea042c28b1c76a7032af7f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":154},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"e6c282927f524a23ba356ef8ccbd6f26",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":154},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81055f28ead54484b95ad406d388d059",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":154},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u50.png"}},
{
              "id":"2e99fe2d496944a998518bd2f7abc288",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":154},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2aa8a2c6b6194872a20b51b3be11bb2f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":154},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u54.png"}},
{
              "id":"367f7d7e4b4543eeb44b3cf75441b7c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":154},
                "size":{
                  "width":192,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7311f56c316447cda2603291c5118230",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":154},
                    "size":{
                      "width":192,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u56.png"}},
{
              "id":"2c9a7fea79504b39a577c177ff1fd0dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":154},
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca0de1e0aa0d43f68754671403df3a60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":154},
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u58.png"}},
{
              "id":"dfc9465c20a04783b007a875f3d543d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":184},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13e7e18aa4ff4bf6a9e6734289bed247",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":184},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u100.png"}},
{
              "id":"ef0008a8818444349b34cd697533bb5c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":184},
                "size":{
                  "width":102,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ede39ae38a564ab3bd0baf7e0805e534",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":102,
                      "y":184},
                    "size":{
                      "width":102,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u100.png"}},
{
              "id":"248ba392ff774075a53cb79c262cc7df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":204,
                  "y":184},
                "size":{
                  "width":174,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbeb92f8a5ea4c48beb7b2cf5ce93a55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":204,
                      "y":184},
                    "size":{
                      "width":174,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u104.png"}},
{
              "id":"078b455659104d5487d57d9e16578a11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":378,
                  "y":184},
                "size":{
                  "width":192,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a04e154dc804f0ebf14b35e733ee170",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":378,
                      "y":184},
                    "size":{
                      "width":192,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u106.png"}},
{
              "id":"5466167ba91b4d34b08ff77bf244c834",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":184},
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c455e75bfbb48bea6d676a280ae3fe7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":184},
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/1、初始化/u108.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "51c34dabc04e4a8a968be6f683330b56":{
      "scriptId":"u0"},
    "d7e80391ae224ceba80c61f01aa37dc2":{
      "scriptId":"u1"},
    "2cd4e0b6edb44c24845a3c4a25d9d696":{
      "scriptId":"u2"},
    "563985062bbd470fa1eb8f9ceea45455":{
      "scriptId":"u3"},
    "516d766687364dc5a503db7c9f736da6":{
      "scriptId":"u4"},
    "53f1abc5011845458adaefdb1b27f908":{
      "scriptId":"u5"},
    "4d3791703f20454ea949c6b6fbf79702":{
      "scriptId":"u6"},
    "0065a7261ab0435ba068d185a29b5e89":{
      "scriptId":"u7"},
    "8c8f0af688424ab3ad8c65aca444e9d6":{
      "scriptId":"u8"},
    "1be623d7b56646d685e5b9cd31cf4bde":{
      "scriptId":"u9"},
    "c7971d7e258f4f3dae011376f814b04e":{
      "scriptId":"u10"},
    "84361a974a274a858dc776cc86690a1c":{
      "scriptId":"u11"},
    "84600017c94a4921a7ba2d26204ccb64":{
      "scriptId":"u12"},
    "208de70dbf1940a786d59197dff16306":{
      "scriptId":"u13"},
    "d8455789af264fb2a836b180145f7e51":{
      "scriptId":"u14"},
    "e870832c349f4b48a681bb7017724949":{
      "scriptId":"u15"},
    "f181bde2d9534179b0e4e73d76ef9687":{
      "scriptId":"u16"},
    "6f8bf7cc8f274f5098ce7c509e44088e":{
      "scriptId":"u17"},
    "1910240bce57482dae07141646b6f1b7":{
      "scriptId":"u18"},
    "e3c8fbf912af4ec39ef61878aad99f48":{
      "scriptId":"u19"},
    "806801922db346b59f41b145f524a69b":{
      "scriptId":"u20"},
    "4e9f95c66264429ab27e731b3a0e62c3":{
      "scriptId":"u21"},
    "4b0938a36d3f45659f3d0b51bba104a3":{
      "scriptId":"u22"},
    "c671cd0d4d5a43ae9eec1b3e8427c907":{
      "scriptId":"u23"},
    "17567bbd95f641df98d8485183acaf94":{
      "scriptId":"u24"},
    "6f0ef1275dbc4451a84b8ce7ae7ac309":{
      "scriptId":"u25"},
    "3640c6c3069d4c7bac65011609598bba":{
      "scriptId":"u26"},
    "8e3211617340407b9840c2409a9c558d":{
      "scriptId":"u27"},
    "4e7f4f7885784d3a8c0cac40800aaf77":{
      "scriptId":"u28"},
    "1c5cd72a6ea84c5bae5874a1e1d4ba39":{
      "scriptId":"u29"},
    "cdc9e2756f324ba580f1b29eeb206bc4":{
      "scriptId":"u30"},
    "ae790335b763486faf90f97b1fd6a3f1":{
      "scriptId":"u31"},
    "b5e657d9c96f438bad1acc7c6494bbb2":{
      "scriptId":"u32"},
    "bd89b18efe6942fc8ba08f27014a20b7":{
      "scriptId":"u33"},
    "aa36c9648f7747339639222dd22aab54":{
      "scriptId":"u34"},
    "9528e8da357a4988958e35ba5c31d6bf":{
      "scriptId":"u35"},
    "0e6249cbc5384674890e4032248eb3f6":{
      "scriptId":"u36"},
    "5a67c3bf04d24d28bf2520830b4f02c1":{
      "scriptId":"u37"},
    "0aac6ae45cc848aa859c4e983217f57d":{
      "scriptId":"u38"},
    "ca3a679c5eb9441eb6cba41671e743f1":{
      "scriptId":"u39"},
    "1adad1ba1c0a47a7a6076df48bdc4bb7":{
      "scriptId":"u40"},
    "b455c81e06344d91ae3de954d4bbba73":{
      "scriptId":"u41"},
    "b036e4171ebd4fe58db504cf21e98b2e":{
      "scriptId":"u42"},
    "83496ebb66134a7fb146b9161d85100c":{
      "scriptId":"u43"},
    "b079d562054b43ff9d00a16fb8f6169a":{
      "scriptId":"u44"},
    "2a90b53ebe8f433fa92cc219eb06fb26":{
      "scriptId":"u45"},
    "d07c527fb5944a7994b954dc394eba06":{
      "scriptId":"u46"},
    "6f42c36172d24a37ac30fc0f6c86b4c4":{
      "scriptId":"u47"},
    "d465d644ff9b42f59a6413957efbb106":{
      "scriptId":"u48"},
    "45f1810dcf754350a219212ee041d0f4":{
      "scriptId":"u49"},
    "cb6bf0d7ee3e45f1a35a2866913af1a3":{
      "scriptId":"u50"},
    "e1a2dca950eb4abaa1a1d11cc6e3a0c2":{
      "scriptId":"u51"},
    "f6ee9dac1d8d4dcc97e0df90d02d7b5b":{
      "scriptId":"u52"},
    "1e0f059c0b9b47d487f9d684216e3083":{
      "scriptId":"u53"},
    "825cb2e7c6ae4ceab518dfc475380df2":{
      "scriptId":"u54"},
    "e1086a9f31e34e3ab89755f596f52772":{
      "scriptId":"u55"},
    "b711e9ccf1ea44ec99f64f3970819d23":{
      "scriptId":"u56"},
    "a3e08feae3c04b108ba557c66bea5b72":{
      "scriptId":"u57"},
    "8913cc7d0d3b4a24a0b1f5e8ca157017":{
      "scriptId":"u58"},
    "cc3543fca25d42ff85dae039ae2f1a56":{
      "scriptId":"u59"},
    "8c5c2a277cf94f7999e5a154d9873d14":{
      "scriptId":"u60"},
    "8ef71020c943436d92cb6f67962b5ba1":{
      "scriptId":"u61"},
    "5b38d9b0d90b41d2b1c4d8d678a5b00d":{
      "scriptId":"u62"},
    "5f07063b7d284e78afb7a34980ff99ad":{
      "scriptId":"u63"},
    "515be87efe9f4827961b133c1a363527":{
      "scriptId":"u64"},
    "f4362b499d734dc983b60cd26eb195d5":{
      "scriptId":"u65"},
    "33e1af2960d34a45a28761f3f4530118":{
      "scriptId":"u66"},
    "e915ba7f38b340eeaf99f0a753c445ac":{
      "scriptId":"u67"},
    "e865c15f3db64c69a4ca37f8b5a366a3":{
      "scriptId":"u68"},
    "1cd151525f5249428b92850cf85ea271":{
      "scriptId":"u69"},
    "990cc7c463b2459491602e43784afbb6":{
      "scriptId":"u70"},
    "dd99422e40d840e1b0d608ffaaf91ae7":{
      "scriptId":"u71"},
    "08da6b090975445d939a4c7dca88df53":{
      "scriptId":"u72"},
    "a256ce0e95cc47f39c4bd148dd468073":{
      "scriptId":"u73"},
    "6b6d6fdf900e4180abb1ecb5d813ccc9":{
      "scriptId":"u74"},
    "9365631dbe3a4c539e401e9c1f51170f":{
      "scriptId":"u75"},
    "0f6c25782fca4c6eb86184e414a40960":{
      "scriptId":"u76"},
    "47686ca3577d40279aef1345cd71d59b":{
      "scriptId":"u77"},
    "174452a2f95447e7bd9cdb3fb0815436":{
      "scriptId":"u78"},
    "e426e8ed34f44ea391f7c95fee795859":{
      "scriptId":"u79"},
    "dca7d695b39a4048b045b9aebf2663a6":{
      "scriptId":"u80"},
    "0cc0265dc64b46c4a317d092067bf210":{
      "scriptId":"u81"},
    "244247b948a542728d706749ef7e925e":{
      "scriptId":"u82"},
    "24e65b4662db4eb2a6e00851750d3c94":{
      "scriptId":"u83"},
    "5467bddfa0da4458a1589bf67f9da9cd":{
      "scriptId":"u84"},
    "d38a5e0288104dd585bf5b3aeca7f5ef":{
      "scriptId":"u85"},
    "253dec0fb88546cfafa47b12fe002159":{
      "scriptId":"u86"},
    "d86fbbc295234485bf8bb72460d9312e":{
      "scriptId":"u87"},
    "4ad9eb7bbb8d4dde97810e7529d6dc5a":{
      "scriptId":"u88"},
    "72dac123d684418baa06f3d6c2641b4b":{
      "scriptId":"u89"},
    "efd6094263d54432a3518e6572931d86":{
      "scriptId":"u90"},
    "fb9536880ea042c28b1c76a7032af7f0":{
      "scriptId":"u91"},
    "e6c282927f524a23ba356ef8ccbd6f26":{
      "scriptId":"u92"},
    "81055f28ead54484b95ad406d388d059":{
      "scriptId":"u93"},
    "2e99fe2d496944a998518bd2f7abc288":{
      "scriptId":"u94"},
    "2aa8a2c6b6194872a20b51b3be11bb2f":{
      "scriptId":"u95"},
    "367f7d7e4b4543eeb44b3cf75441b7c1":{
      "scriptId":"u96"},
    "7311f56c316447cda2603291c5118230":{
      "scriptId":"u97"},
    "2c9a7fea79504b39a577c177ff1fd0dc":{
      "scriptId":"u98"},
    "ca0de1e0aa0d43f68754671403df3a60":{
      "scriptId":"u99"},
    "dfc9465c20a04783b007a875f3d543d4":{
      "scriptId":"u100"},
    "13e7e18aa4ff4bf6a9e6734289bed247":{
      "scriptId":"u101"},
    "ef0008a8818444349b34cd697533bb5c":{
      "scriptId":"u102"},
    "ede39ae38a564ab3bd0baf7e0805e534":{
      "scriptId":"u103"},
    "248ba392ff774075a53cb79c262cc7df":{
      "scriptId":"u104"},
    "bbeb92f8a5ea4c48beb7b2cf5ce93a55":{
      "scriptId":"u105"},
    "078b455659104d5487d57d9e16578a11":{
      "scriptId":"u106"},
    "9a04e154dc804f0ebf14b35e733ee170":{
      "scriptId":"u107"},
    "5466167ba91b4d34b08ff77bf244c834":{
      "scriptId":"u108"},
    "3c455e75bfbb48bea6d676a280ae3fe7":{
      "scriptId":"u109"}}});